name: final_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_sizer: ^3.3.0+1
  flutter_svg:
  gap:
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http_interceptor:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/SvgIcons/
    - assets/fonts/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Regular.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
          weight: 700
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 700
